#ddev-generated
hooks:
  post-import-db:
    - exec: /var/www/html/.ddev/pimp-my-shell/hooks/post-import-db.sh
webimage_extra_packages:
  - ansilove
  - bash-completion
  - boxes
  - bsdmainutils
  - build-essential
  - certbot
  - colorized-logs
  - cowsay
  - dialog
  - dnsutils
  - figlet
  - htop
  - libarchive-tools
  - lolcat
  - lua5.4
  - man-db
  - moreutils
  - net-tools
  - pipx
  - pv
  - screen
  - vim-nox
web_environment:
  - COLORTERM=${COLORTERM}
  - TERM=${TERM}
